import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedFeatured {
  final List<FeaturedModel> results;

  AutogeneratedFeatured({this.results});

  factory AutogeneratedFeatured.fromJson(Map<String, dynamic> json) {
    List<FeaturedModel> temp;
    if (json['results'] != null) {
      temp = <FeaturedModel>[];
      json['results'].forEach((v) {
        temp.add(FeaturedModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedFeatured(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class FeaturedModel extends Equatable {
  final int id;
  final String name;

  FeaturedModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory FeaturedModel.fromJson(Map<String, dynamic> json) {
    return FeaturedModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
