import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedArticle {
  final List<ArticleModel> results;

  AutogeneratedArticle({this.results});

  factory AutogeneratedArticle.fromJson(Map<String, dynamic> json) {
    List<ArticleModel> temp;
    if (json['results'] != null) {
      temp = <ArticleModel>[];
      json['results'].forEach((v) {
        temp.add(ArticleModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedArticle(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ArticleModel extends Equatable {
  final int id;
  final String name;

  ArticleModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ArticleModel.fromJson(Map<String, dynamic> json) {
    return ArticleModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
